### ISSUE TITLE
Unable to create prescribed conda environment

### ISSUE THREAD

**Issue by ctcisar** [bioFAM/FISHFactor#4]
I was looking to set up a conda environment to run FISHFactor in, and cannot generate one using the provided environment.yml file.

<details><summary>Running the file as-is generates the following error: (click to expand)</summary>

```
$ conda env create -f environment.yml 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 101, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/specs/__init__.py", line 46, in detect
        if spec.can_handle():
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/env.py", line 169, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return _yaml_safe().load(string)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/main.py", line 434, in load
        return constructor.get_single_data()
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
        node = self.composer.get_single_node()
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
        document = self.compose_document()
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
        node = self.compose_node(None, None)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 141, in compose_node
        node = self.compose_sequence_node(anchor)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 185, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 141, in compose_node
        node = self.compose_sequence_node(anchor)
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 184, in compose_sequence_node
        while not self.parser.check_event(SequenceEndEvent):
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 146, in check_event
        self.current_event = self.state()
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 530, in parse_block_sequence_entry
        if self.scanner.check_token(BlockEntryToken):
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 174, in check_token
        while self.need_more_tokens():
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 211, in need_more_tokens
        self.stale_possible_simple_keys()
      File "/home/cecilia/miniconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 360, in stale_possible_simple_keys
        raise ScannerError(
    ruamel.yaml.scanner.ScannerError: while scanning a simple key
      in "<unicode string>", line 281, column 1:
        <<<<<<< HEAD
        ^ (line: 281)
    could not find expected ':'
      in "<unicode string>", line 282, column 1:
        prefix: /data/florin/miniconda3/ ... 
        ^ (line: 282)

`$ /home/cecilia/miniconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/cecilia/miniconda3/bin/conda
             CONDA_PREFIX=/home/cecilia/miniconda3
           CONDA_PREFIX_1=/home/cecilia/miniconda3
           CONDA_PREFIX_2=/home/cecilia/miniconda3/envs/SpiceMix
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/home/cecilia/miniconda3/bin/python
               CONDA_ROOT=/home/cecilia/miniconda3
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/cecilia/.local/bin:/home/cecilia/miniconda3/bin:/home/cecilia/mi
                          niconda3/condabin:/home/cecilia/.local/bin:/usr/local/sbin:/usr/local/
                          bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bi
                          n:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/cecilia/miniconda3
            shell level : 3
       user config file : /home/cecilia/.condarc
 populated config files : /home/cecilia/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.19.17=0
                          __unix=0=0
       base environment : /home/cecilia/miniconda3  (writable)
      conda av data dir : /home/cecilia/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/cecilia/miniconda3/pkgs
                          /home/cecilia/.conda/pkgs
       envs directories : /home/cecilia/miniconda3/envs
                          /home/cecilia/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Linux/5.19.17-051917-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```
</details>

After removing all the text in the file after the line `<<<<<<< HEAD`, conda is unable to resolve package versions: [output log](https://pastebin.com/5HtH6WZC)

I am on Ubuntu 22.04.2 LTS and using miniconda 22.11.1, and this was verified on another machine with Ubuntu 18.04.6 LTS and miniconda 4.13.0

**Comment by florinwalter** [comment]
Thanks for opening the issue, you were right that it was not possible to install it this way. Could you try again now? It worked on my local machine.

**Comment by ctcisar** [comment]
Yes, it works now! Thanks.
